baseURL: 'https://tgcg.xyz'
languageCode: 'en-us'
title: 'The Good Code Guy'
theme: 'smol'

params:
  subtitle: "A personal blog about whatever I want"
  dateFmt: "02.01.2006 15:04"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1

    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2

    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3

  footer:
    - name: Github
      url: https://github.com/example
      weight: 1

    - name: LinkedIn
      url: https://example.com/@user
      weight: 2

