#+title: Truth In Tension

* There is Truth in Tension

We live in a world that dominated by the too-quick-to-offend and the offended-too-quickly.

When in reality, we live in a multi-faceted world; each colored by the unique experiences of the individual.

For whatever reason (there are multiple) our capacity to understand this nuance in experience has lagged behind our access to nigh-infinite volumes of information.


The result is a simple breakdown in society, with sects colored by their worldviews which are in turn orchestrated by an unconscious engagement machine, carefully feeding whatever data fuels your focus and engagement.

In the light, such technologically doped filtering is a wonderful godsend -- instantly we can meet with products we love, information we need, people we like, and perspectives we harbor; in an instant we find ourselves coddled with whatever cranial comforts we desire.

In the dark though, our diet becomes too mono and this feed of comfort isolates us in a mental prison colored by the boundaries of our own taste. In such a world, we feel difference as pain and pain lends itself to our darkest emotions -- rage, sorrow, hatred, and violence.

The breakdown we +see+ feel in society is borne simply of this weakened capacity to empathize with the ***hard*** reality that we each have a separate experience and that, by immutable extension, we each have a worldview that varies from all others. This is in an inescapable truth, possibly the "capital-T" truth -- we each have a different perspective.


That difference in perspective leads all the way to differences in our preferred genre of music to the fundamental ethics of society as a whole. Our failure to realize this, especially in a moment of heightened emotion, is chief in our failure to understand, empathize, connect with, and grow alongside others. It is the heart of the political divide and the essence of human violence.


The reality is that there is *Truth in Tension*; the cornucopia of perspectives necessitate variety in perspective and variety in perspective necessitates disagreement; hence you will not find truth without tension.


* How a "Safe" society became the dangerous one

TODO - a note about how our society swung (positively) toward a place of intentional empathy and preserving space for difference in perspective but went too far and now difference in perspective are shamed again
